# AppDimens Games
org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

kotlin.code.style=official

android.useAndroidX=true
android.nonTransitiveRClass=true

GROUP=io.github.bodenberg
POM_ARTIFACT_ID=appdimens-games
appdimens.version=3.0.0
VERSION_NAME=3.0.0

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
